### ISSUE TITLE
Flink master port is not forwarded by default

### ISSUE THREAD

**Issue by youssefmamdouh** [big-data-europe/docker-flink#10]
A simple edit to docker-compose.yaml needs to be done
`    ports:
     - "8081:8081"`
That's just to make the dashboard accessible from the localhost.

**Comment by GezimSejdiu** [comment]
Thanks @youssefmamdouh for your suggestion. I just merged branch 1.1.3-hadoop2.7 (where port forwarding was already implemented) into master (https://github.com/big-data-europe/docker-flink/blob/master/docker-compose.yml#L12 ).
