### ISSUE TITLE
docker-compose tag not up-to-date

### ISSUE THREAD

**Issue by eisenreich** [big-data-europe/docker-flink#13]
The tag of _bde2020/flink-master_ and _bde2020/flink-worker_ image does not exist anymore! Please update.

**Comment by GezimSejdiu** [comment]
Hi @eisenreich ,

many thanks for letting us know that the tags haven't been updated on the docker.hub. It is due to the dependencies while building a base image. I will trigger them manually and let you know when they are updated.

Best regards,

**Comment by GezimSejdiu** [comment]
Done! 
[bde2020/flink-master](https://cloud.docker.com/u/bde2020/repository/docker/bde2020/flink-master), [bde2020/flink-worker](https://cloud.docker.com/u/bde2020/repository/docker/bde2020/flink-worker)
Give it a try and let me know.

Best regards,

**Comment by GezimSejdiu** [comment]
I'm going to close these issue since the tags have been updated on the hub. Let me know in case there is something else missing. 

Best regards,
