### ISSUE TITLE
Is this deprecated? 

### ISSUE THREAD

**Issue by xixici** [big-data-europe/docker-flink#16]
Is this deprecated? 
The last commit is 19 Feb 2019. 
Is there a way to get the latest docker image?
Thx

**Comment by GezimSejdiu** [comment]
Hey @xixici , 

thanks a lot for your question. I apologize for the late reply. Had no time to review this :( -- but I just did submit the very latest docker image for Flink 1.12.2 bundled with hadoop 3.2. 

Please, give it a try and do let me know if you are having any issues.

Best regards,

**Comment by xixici** [comment]
It doesn't matter. Thanks your contribute. I have no chance to try it now. Hope this can help others.
