### ISSUE TITLE
Incorrect number of task slots after restart services

### ISSUE THREAD

**Issue by trushev** [big-data-europe/docker-flink#18]
Hi, thank you for the image. I found a bug and would like to share it with you

#### Steps to reproduce

1. in docker-compose.yml set
```yml
FLINK_NUM_TASK_SLOTS=12
```

2. then run
```bash
docker-compose up -d
```

3. finally, restart services
```bash
docker-compose restart
```
expected task slots 12
actual task slots 122

#### Possible solution

the problem place in worker/worker.sh
it can be fixed by replacing

    sed -i -e "s/taskmanager.numberOfTaskSlots: 1/taskmanager.numberOfTaskSlots: ${FLINK_NUM_TASK_SLOTS}/g" /usr/local/flink/conf/flink-conf.yaml

with

    sed -i -e "s/taskmanager.numberOfTaskSlots: [0-9]\+/taskmanager.numberOfTaskSlots: ${FLINK_NUM_TASK_SLOTS}/g" /usr/local/flink/conf/flink-conf.yaml

i.e. by changing "1" to "[0-9]\\+"

**Comment by GezimSejdiu** [comment]
Hey @trushev ,

cool. Nice catch and thanks a lot for reporting it. Would you (and have time) like to contribute this change so that I can marge it? We give credit where credit's are due ;)

Cheers,

Gezim

**Comment by trushev** [comment]
Hello @GezimSejdiu, thanks for the reply:)
I have verified the change by `build.sh` locally: `bde2020/flink-worker` and `bde2020/flink-master` are ok.
But the build on CI failed due to an error related to `sbt-1.4.1.deb`. I guess it's not related to the change

**Comment by trushev** [comment]
Looks like `dl.bintray.com` does not work anymore. So `curl -L -o sbt-$SBT_VERSION.deb http://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb` in `sbt/Dockerfile` failed

**Comment by GezimSejdiu** [comment]
Great! Thanks a lot @trushev for your contribution. Reg. sbt -- I can also take that up and fix it. If you already have a solution (fix) feel free to also push it :) -- but only if you have time and can/have the solution already.

Let me know so that I can plan the merge and fix this issue with SBT.

Once more, thanks a lot for your contribution.

Cheers, 
Gezim

**Comment by trushev** [comment]
@GezimSejdiu 
There is a solution but I'm not sure if the change is acceptable. Anyway, I have opened PR :) https://github.com/big-data-europe/docker-flink/pull/20
