### ISSUE TITLE
flink-worker has status Exited (0) right after docker run

### ISSUE THREAD

**Issue by gmouchakis** [big-data-europe/docker-flink#5]
I'm trying to setup a Flink cluster using docker run commands found in READE.

First I deploy the master using

`$ docker run --name flink-master -h flink-master -e ENABLE_INIT_DAEMON=false -d bde2020/flink-master:0.10.1-hadoop2.7`
`$ docker logs flink-master`
Starting Flink webclient
Missing streaming mode (batch|streaming) argument. Using 'batch'.
Starting jobmanager daemon on host flink-master.
Cluster started.

Then I deploy two workers

`$ docker run --name flink-worker-1 --link flink-master:flink-master -e ENABLE_INIT_DAEMON=false -d bde2020/flink-worker:0.10.1-hadoop2.7`
`$ docker logs flink-worker-1`
Missing streaming mode (batch|streaming). Using 'batch'.
Starting taskmanager daemon on host 80bb50f151cd.
`$ docker run --name flink-worker-2 --link flink-master:flink-master -e ENABLE_INIT_DAEMON=false -d bde2020/flink-worker:0.10.1-hadoop2.7`
`$ docker logs flink-worker-2`
Missing streaming mode (batch|streaming). Using 'batch'.
Starting taskmanager daemon on host 6cda68eb7512.

When I check the container status both workers seem to exit right after they are deployed.

`$ sudo docker ps -a`

CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                      PORTS                        NAMES
6cda68eb7512        bde2020/flink-worker:0.10.1-hadoop2.7   "/bin/bash /worker.sh"   7 seconds ago       Exited (0) 6 seconds ago                                 flink-worker-2
80bb50f151cd        bde2020/flink-worker:0.10.1-hadoop2.7   "/bin/bash /worker.sh"   13 seconds ago      Exited (0) 13 seconds ago                                flink-worker-1
c69c45ebe9a1        bde2020/flink-master:0.10.1-hadoop2.7   "/bin/bash /master.sh"   25 seconds ago      Up 24 seconds               22/tcp, 6123/tcp, 8080/tcp   flink-master

Is this the proper way to deploy the cluster? Should I do something else to keep the workers alive?

**Comment by GezimSejdiu** [comment]
Hi @gmouchakis , thanks for your valuable feedback.
In order to run flink-docker as a standalone cluster, you should specify an entry point into /etc/hosts :

```
<IP>   flink-master
```

or you could give as a -h directly your hostIP or hostname.
Please, could you try if out now, since they are working and this issue is fixed with a latest commits.
Many thanks.

**Comment by gmouchakis** [comment]
Seems working now, thanks!
